version: "3.4"
services: 
  db:
    image: mysql:8.0.28
    container_name: db
    command: "mysqld --default-authentication-plugin=mysql_native_password"
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: rest
      MYSQL_PASSWORD: docker
      MYSQL_RANDOM_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: docker    
      TZ: America/Sao_Paulo 
    ports: 
      - 3308:3306
    expose: [3308]
    restart: always