version: "3.4"

services: 
 
  rest-udemy:
    container_name: rest-udemy
    build: ./restudemy
    command: "mvn clean spring-boot:run"
    depends_on: 
      db:
        condition: service_started
    environment: 
      SPRING_BOOT_ENVIRONMENT: Production
      TZ: America/Sao_Paulo
    # image: diegocgsi/rest-udemy
    # links: 
    #   - db
    networks: 
      - udemy-network
    ports: 
      - "8080:8080"
    expose: [8080]
    restart: always
    volumes: 
      - "./restudemy:/restudemy"
      - "~/.m2:/root/.m2"
    working_dir: /restudemy
  
  db:
    image: mariadb:latest
    container_name: db
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: rest
      MYSQL_PASSWORD: docker
      MYSQL_RANDOM_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: docker    
      TZ: America/Sao_Paulo    
    networks: 
      - udemy-network
    ports: 
      - 3308:3306
    expose: [3308]
    restart: always
    command: "mysqld --default-authentication-plugin=mysql_native_password"
networks: 
  udemy-network: 
    driver: bridge